package heapsort;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

public class HeapView extends javax.swing.JPanel {
    int[] content;
    
    public HeapView() {
        content = new int[45];//new Heapsort(45, false).content;
        this.setDoubleBuffered(true);
        initComponents();
    }
    
    int calcMaxTier() {
        return (int)StrictMath.round(StrictMath.log(content.length) / StrictMath.log(2));
    }
    
    @Override
    public void paint(Graphics g) {
        Graphics2D g2 = (Graphics2D)g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
        int max = calcMaxTier();
        int yoffset = (this.getHeight() - 30) / (max - 1);
        for(int tier = 1; tier <= max; tier++) {
            int count = (int)StrictMath.round(StrictMath.pow(2, tier - 1));
            int offset = this.getWidth() / (count + 1);
            int ypos = 15 + yoffset * (tier - 1);
            for(int slot = 1; slot <= count; slot++) {
                int middlePosition = slot * offset;
                int index = count - 2 + slot;
                if(index >= content.length) {
                    break;
                }
                if(index > 0) {
                    g2.drawLine(middlePosition, ypos, ((slot + 1) / 2) * (this.getWidth() / (count / 2 + 1)), (10 + yoffset * (tier - 2)));
                }
                g2.fillOval(middlePosition - 15, ypos - 15, 30, 30);
                g2.setColor(Color.white);
                g2.drawString("" + content[index], middlePosition - 10, ypos + 5);
                g2.setColor(Color.black);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
